name: Spring Boot CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        

    steps:
    - name: 자바 17 버전 설치
      uses: actions/setup-java@v3
      with:
      # JDK 배포판 지정
        distribution: 'temurin'
        java-version: '17'

    - name: 소스 코드 체크아웃
      uses: actions/checkout@v3

    - name: gradlew 프로젝트 의존성 설치
      run: chmod +x gradlew

    - name: 데이터베이스 초기화 및 실행 테스트
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${{ secrets.DB_NAME }}?serverTimezone=Asia/Seoul
        SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: ./gradlew build --info
